import React from 'react';
import { useAuth } from '../../context/AuthContext';

// Template 1: Modern Professional
export const ModernTemplate = ({ resume }) => {
  const { user } = useAuth();
  
  // Check if resume and content exist
  if (!resume || !resume.content) {
    return (
      <div className="text-center py-8 text-gray-500">
        <p>Resume content not available. Please edit and add content to your resume.</p>
      </div>
    );
  }
  
  // Parse markdown-like content
  const parseContent = (content) => {
    const sections = [];
    let currentSection = { title: 'Summary', content: [] };
    
    const lines = content.split('\n');
    
    for (const line of lines) {
      if (line.startsWith('# ')) {
        if (currentSection.content.length > 0) {
          sections.push({ ...currentSection });
        }
        currentSection = { title: line.substring(2), content: [] };
      } else if (line.trim()) {
        currentSection.content.push(line);
      }
    }
    if (currentSection.content.length > 0) {
      sections.push(currentSection);
    }
    
    return sections;
  };
  
  const sections = parseContent(resume.content);
  
  return (
    <div className="bg-white shadow-lg rounded-lg overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-primary-600 to-primary-800 px-8 py-6 text-white">
        <h1 className="text-3xl font-bold">{resume.title || 'Professional Resume'}</h1>
        <p className="text-primary-100 mt-1">Version {resume.version || 1}</p>
      </div>
      
      {/* Content */}
      <div className="p-8 space-y-6">
        {sections.map((section, idx) => (
          <div key={idx}>
            <h2 className="text-xl font-bold text-gray-800 border-b-2 border-primary-500 pb-2 mb-3">
              {section.title}
            </h2>
            <div className="space-y-2">
              {section.content.map((line, lineIdx) => {
                if (line.startsWith('- ')) {
                  return (
                    <li key={lineIdx} className="text-gray-700 ml-4">
                      {line.substring(2)}
                    </li>
                  );
                }
                if (line.includes('**') && line.includes('**')) {
                  const boldMatch = line.match(/\*\*(.*?)\*\*/);
                  if (boldMatch) {
                    const parts = line.split(/\*\*.*?\*\*/);
                    return (
                      <p key={lineIdx} className="text-gray-700">
                        {parts[0]}<strong className="text-gray-900">{boldMatch[1]}</strong>{parts[1] || ''}
                      </p>
                    );
                  }
                }
                return <p key={lineIdx} className="text-gray-700">{line}</p>;
              })}
            </div>
          </div>
        ))}
      </div>
      
      {/* Footer */}
      <div className="bg-gray-50 px-8 py-4 border-t border-gray-200">
        <p className="text-xs text-gray-500 text-center">
          Generated by HireMind • {new Date().toLocaleDateString()}
        </p>
      </div>
    </div>
  );
};

// Template 2: Minimal Clean
export const MinimalTemplate = ({ resume }) => {
  // Check if resume and content exist
  if (!resume || !resume.content) {
    return (
      <div className="text-center py-8 text-gray-500">
        <p>Resume content not available. Please edit and add content to your resume.</p>
      </div>
    );
  }

  return (
    <div className="bg-white shadow-lg rounded-lg p-8">
      <div className="border-b-2 border-gray-200 pb-4 mb-6">
        <h1 className="text-3xl font-light text-gray-800">{resume.title || 'Resume'}</h1>
        <p className="text-sm text-gray-500 mt-1">Version {resume.version || 1}</p>
      </div>
      
      <div className="prose prose-gray max-w-none">
        <div className="whitespace-pre-wrap font-sans text-gray-700">
          {resume.content.split('\n').map((line, i) => {
            if (line.startsWith('# ')) {
              return <h2 key={i} className="text-xl font-semibold text-gray-800 mt-4 mb-2">{line.substring(2)}</h2>;
            }
            if (line.startsWith('## ')) {
              return <h3 key={i} className="text-lg font-medium text-gray-700 mt-3 mb-1">{line.substring(3)}</h3>;
            }
            if (line.startsWith('- ')) {
              return <li key={i} className="ml-4 text-gray-600">{line.substring(2)}</li>;
            }
            if (line.trim() === '') {
              return <div key={i} className="h-2"></div>;
            }
            return <p key={i} className="text-gray-600 mb-1">{line}</p>;
          })}
        </div>
      </div>
    </div>
  );
};

// Template 3: Corporate Professional
export const CorporateTemplate = ({ resume }) => {
  // Check if resume and content exist
  if (!resume || !resume.content) {
    return (
      <div className="text-center py-8 text-gray-500">
        <p>Resume content not available. Please edit and add content to your resume.</p>
      </div>
    );
  }

  return (
    <div className="bg-gray-50 shadow-lg rounded-lg overflow-hidden">
      <div className="bg-gray-900 px-8 py-6 text-white">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">{resume.title || 'Professional Resume'}</h1>
            <p className="text-gray-400 mt-1">Version {resume.version || 1}</p>
          </div>
          <div className="text-right">
            <p className="text-sm text-gray-400">Created with HireMind</p>
          </div>
        </div>
      </div>
      
      <div className="p-8">
        <div className="grid grid-cols-1 gap-6">
          {resume.content.split('\n\n').map((paragraph, idx) => {
            if (paragraph.startsWith('# ')) {
              return (
                <div key={idx}>
                  <h2 className="text-lg font-semibold text-gray-800 border-l-4 border-primary-600 pl-3 mb-2">
                    {paragraph.substring(2)}
                  </h2>
                </div>
              );
            }
            return (
              <p key={idx} className="text-gray-600 leading-relaxed">
                {paragraph}
              </p>
            );
          })}
        </div>
      </div>
    </div>
  );
};

// Template Selector Component
export const TemplateSelector = ({ selectedTemplate, onSelect }) => {
  const templates = [
    { id: 'modern', name: 'Modern Professional', icon: '🎨', description: 'Colorful header, clean layout' },
    { id: 'minimal', name: 'Minimal Clean', icon: '✨', description: 'Simple, elegant, focus on content' },
    { id: 'corporate', name: 'Corporate Classic', icon: '💼', description: 'Traditional, professional look' }
  ];
  
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
      {templates.map((template) => (
        <button
          key={template.id}
          onClick={() => onSelect(template.id)}
          className={`p-4 rounded-lg border-2 transition-all text-left ${
            selectedTemplate === template.id
              ? 'border-primary-500 bg-primary-50'
              : 'border-gray-200 hover:border-gray-300'
          }`}
        >
          <div className="text-2xl mb-2">{template.icon}</div>
          <h4 className="font-semibold text-gray-900">{template.name}</h4>
          <p className="text-xs text-gray-500 mt-1">{template.description}</p>
        </button>
      ))}
    </div>
  );
};